sudo: false

language: node_js
node_js:
  - 4
  - 6
  - 8
  - node

before_install:
  - npm install codecov.io coveralls nwb

script: 
  - npm test --coverage

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

#Jobs that run after the tests
jobs:
  include:

    #Build the project
    - stage: Build
      node_js: 8
      script: 
       - echo "Building project"
       - npm run build

    #Deploy project to NPM
    - stage: Deploy NPM
      node_js: 8
      script: echo "Deploying project to NPM"
      deploy:
        provider: npm
        skip_cleanup: true
        api_key:  $NPM_TOKEN

    #Deploy project to Surge
    - stage: Deploy Surge
      node_js: 8
      script: echo "Deploying Demo to Surge"
      deploy:
        provider: surge
        skip_cleanup: true
        project: ./demo/dist/
        domain: react-photostream.surge.sh


  - 

branches:
  only:
    - master