sudo: false

language: node_js
node_js:
  - 4
  - 6
  - 8

before_install:
  - npm install codecov.io coveralls nwb

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

deploy:
  - provider: surge
    skip_cleanup: true
    project: ./demo/dist/
    domain: react-photostream.surge.sh
  - provider: npm
    skip_cleanup: true
    api_key:  $NPM_TOKEN

branches:
  only:
    - master